<a href="https://colab.research.google.com/github/rajendran-official/AI_ML_COURSE_ICT/blob/NumPy/Manappuram_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [2]:
import numpy as np

In [3]:
arr = np.array([2,3,1,5,3,2,1,6])

In [4]:
print(arr)

[2 3 1 5 3 2 1 6]


In [5]:
#Attributes and Methods
arr.ndim # single row so it gives 1 as output

1

In [8]:
arr.shape# it returns how many columns in the rows

(8,)

In [9]:
arr.dtype # it returns array datatype

dtype('int64')

In [11]:
type(arr) # ndimension array in numpy

numpy.ndarray

In [13]:
#2 dimension array --> we called as matrix
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.base


In [18]:
arr2.ctypes

In [19]:
arr2.data

In [20]:
arr2.dtype

dtype('int64')

In [21]:
type(arr2)

numpy.ndarray

In [22]:
arr2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [23]:
arr2.strides

(32, 8)

In [24]:
arr2.size

8

In [25]:
arr2.shape

(2, 4)

In [26]:
arr2.real

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr2.ndim

2

In [30]:
arr.ndim

1

In [31]:
arr2.mT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [32]:
arr2.nbytes

64

In [33]:
arr2.itemsize

8

In [34]:
arr3 = np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr4 = np.arange(1,10)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr3 = np.arange(1,11,2)
arr3

array([1, 3, 5, 7, 9])

In [41]:
arr3=np.arange(4,20)
arr3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
arr3.shape

(16,)

In [43]:
arr3.reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
#purple cube is function
#blue color rectangle  is attribute

In [45]:
arr3 = arr3.reshape(4,4)
arr3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [46]:
arr3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
#Array Slicing
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[4]

np.int64(4)

In [51]:
arr[0]

np.int64(0)

In [52]:
arr[-1]

np.int64(15)

In [53]:
arr[:5]

array([0, 1, 2, 3, 4])

In [54]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
arr[[2,3,4]]

array([2, 3, 4])

In [57]:
arr2= np.array([[-7,5,-2,4],[5,2,7,3],[10,-13,-3,5]])

In [58]:
print(arr2)

[[ -7   5  -2   4]
 [  5   2   7   3]
 [ 10 -13  -3   5]]


In [59]:
arr2[2]

array([ 10, -13,  -3,   5])

In [60]:
arr2[0]

array([-7,  5, -2,  4])

In [61]:
arr2[1]

array([5, 2, 7, 3])

In [62]:
arr2[[1,2]]

array([[  5,   2,   7,   3],
       [ 10, -13,  -3,   5]])

In [63]:
arr2[:,1]

array([  5,   2, -13])

In [64]:
arr2[:,0]

array([-7,  5, 10])

In [66]:
arr2[:,3]

array([4, 3, 5])

In [67]:
arr3 = np.arange(10, 82,2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [68]:
arr3.shape

(36,)

In [69]:
arr3 = arr3.reshape(6,6)
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]


In [71]:
arr3[:,[0,3]]

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [73]:
arr3[:2,:]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [76]:
arr3[:,[0,3]] # all rows , 0 and 3 rd colum

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [77]:
arr3[:2,:] # zero to 2nd row, all columns

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [78]:
#Numerical operations

arr3.sum()

np.int64(1620)

In [79]:
np.mean(arr3)

np.float64(45.0)

In [80]:
np.median(arr3)

np.float64(45.0)

In [81]:
arr3.mean(axis=1)

array([15., 27., 39., 51., 63., 75.])

In [82]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [83]:
arr3.mean(axis=0) # column wise mean

array([40., 42., 44., 46., 48., 50.])

In [87]:
arr3.mean(axis=0)

array([40., 42., 44., 46., 48., 50.])

In [89]:
arr3+5

array([[15, 17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35, 37],
       [39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61],
       [63, 65, 67, 69, 71, 73],
       [75, 77, 79, 81, 83, 85]])

In [90]:
arr3-4

array([[ 6,  8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50, 52],
       [54, 56, 58, 60, 62, 64],
       [66, 68, 70, 72, 74, 76]])

In [91]:
arr3*5

array([[ 50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160],
       [170, 180, 190, 200, 210, 220],
       [230, 240, 250, 260, 270, 280],
       [290, 300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390, 400]])

In [93]:
arr3[5]=99
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [99, 99, 99, 99, 99, 99]])

In [94]:
np.abs(arr3)# display only postive value

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [99, 99, 99, 99, 99, 99]])

In [95]:
np.sqrt(arr3)

array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
        4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
        5.65685425],
       [5.83095189, 6.        , 6.164414  , 6.32455532, 6.4807407 ,
        6.63324958],
       [6.78232998, 6.92820323, 7.07106781, 7.21110255, 7.34846923,
        7.48331477],
       [7.61577311, 7.74596669, 7.87400787, 8.        , 8.1240384 ,
        8.24621125],
       [9.94987437, 9.94987437, 9.94987437, 9.94987437, 9.94987437,
        9.94987437]])

In [97]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [98]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [99]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [101]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [99, 99, 99, 99, 99, 99]])

In [103]:
arr3.T # transpose --> rows into columns and columns into rows

array([[10, 22, 34, 46, 58, 99],
       [12, 24, 36, 48, 60, 99],
       [14, 26, 38, 50, 62, 99],
       [16, 28, 40, 52, 64, 99],
       [18, 30, 42, 54, 66, 99],
       [20, 32, 44, 56, 68, 99]])

In [107]:
a = np.zeros((4,4))
b = np.ones((4,4))

In [108]:
np.vstack((a,b)) # vertical stack

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [109]:
np.hstack((a,b)) # horizontal stack

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [110]:
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [99, 99, 99, 99, 99, 99]])

In [111]:
arr3.flatten() # to convert two dimension array into one dimension array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 99, 99, 99, 99,
       99, 99])

In [113]:
#Random number generation
np.random.randint(50)

47

In [116]:
np.random.randint(12,60)

38

In [117]:
np.random.randint(12,60,5)

array([58, 26, 22, 25, 34])

In [121]:
arr4= np.arange(1,21)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [122]:
arr4.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [124]:
a = np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
a[5]=100
a

array([  0.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.])

In [130]:
random_array = np.random.randint(1, 101, 15)

In [131]:
print(random_array)

[35 83 71 48 15 61 50 68 11 33 86 47  6 78 21]


In [132]:
print(np.min(random_array))

6


In [133]:
print(np.max(random_array))

86


In [134]:
print(np.mean(random_array))

47.53333333333333


In [136]:
print(np.std(random_array))

25.837612548806096


In [137]:
import numpy as np

# Sample sales and costs arrays
sales = np.array([1000, 1200, 800, 1500, 900])
costs = np.array([700, 900, 600, 1000, 750])

# Calculate profit
profit = sales - costs

# Calculate profit percentage
# To avoid division by zero, we can use np.where or add a small epsilon
profit_percentage = (profit / sales) * 100

print("Sales Array:", sales)
print("Costs Array:", costs)
print("Profit Array:", profit)
print("Profit Percentage Array:", profit_percentage)

Sales Array: [1000 1200  800 1500  900]
Costs Array: [ 700  900  600 1000  750]
Profit Array: [300 300 200 500 150]
Profit Percentage Array: [30.         25.         25.         33.33333333 16.66666667]
